#!/usr/bin/env bash
#
# Transfer a file from client to server

if (( $# < 3 ))
then
  printf 'Usage: %s PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\n' "${0##*/}"
  exit 1
fi

if (( $# < 4 ))
then
  scp -o 'StrictHostKeyChecking No' -- "$1" "$3@$2:"
else
  scp -o 'StrictHostKeyChecking No' -i "$4" -- "$1" "$3@$2:"
fi
