#!/usr/bin/env bash
#
# Install NGINX on my server

apt-get -y update
apt-get -y install nginx

cat > /var/www/html/index.html << 'EOF' 
<html>
  <head>
    <title>Holberton School</title>
  </head>
  <body>
    <p>Holberton School for the win!</p>
  </body>
</html>
EOF

service nginx start

ufw allow 'Nginx HTTP'
