#!/usr/bin/env bash
#
# Install NGINX on my server

NYANCAT='https://www.youtube.com/watch?v=QH2-TGUlwu4'
PATTERN='^\troot /var/www/html;$'
REPLACE="& \
rewrite ^/redirect_me ${NYANCAT} permanent; \
error_page 404 /custom_404.html; \
location = /custom_404.html { \
root /usr/share/nginx/html; \
internal; \
}"

apt-get -y update
apt-get -y install nginx

sed -i "s@${PATTERN}@${REPLACE}@" /etc/nginx/sites-available/default

cat > /var/www/html/index.html << 'EOF' 
<html>
  <head>
    <title>Holberton School</title>
  </head>
  <body>
    <p>Holberton School for the win!</p>
  </body>
</html>
EOF

cat > /usr/share/nginx/html/custom_404.html << 'EOF' 
<html>
  <head>
    <title>Page Not Found</title>
  </head>
  <body>
    <p>Ceci n'est pas une page</p>
  </body>
</html>
EOF

service nginx start

ufw allow 'Nginx HTTP'
